"""empty message

Revision ID: d773d5cd8f89
Revises:
Create Date: 2025-02-07 06:58:36.036253

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d773d5cd8f89"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipt",
        sa.Column("receipt_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("items", sa.JSON(), nullable=True),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("date", sa.Integer(), nullable=False),
        sa.Column("currency", sa.Enum("EUR", name="currency"), nullable=False),
        sa.Column(
            "market",
            sa.Enum("ALDI", "LIDL", "NETTO", "REWE", "EDEKA", "KAUFLAND", "PENNY", "REAL", name="market"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("receipt_id"),
    )
    op.create_index(op.f("ix_receipt_date"), "receipt", ["date"], unique=False)
    op.create_index(op.f("ix_receipt_market"), "receipt", ["market"], unique=False)
    op.create_index(op.f("ix_receipt_user_id"), "receipt", ["user_id"], unique=False)
    op.create_table(
        "user",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=True),
        sa.Column("last_login", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_index(op.f("ix_user_is_active"), "user", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_is_active"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_receipt_user_id"), table_name="receipt")
    op.drop_index(op.f("ix_receipt_market"), table_name="receipt")
    op.drop_index(op.f("ix_receipt_date"), table_name="receipt")
    op.drop_table("receipt")
    # ### end Alembic commands ###
