services:
  smart_cart:
    environment:
      PORT: 1000
      ENVIRONMENT: "local"
      PYTHONPATH: "/app"
      WAIT_HOSTS: db:5432
      TABS_SCANNER_API_KEY: ${TABS_SCANNER_API_KEY}
    env_file:
      - env_files/base.env
    build: .
    ports:
      - "1000:1000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    env_file:
      - env_files/base.env
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local