name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install flake8 pytest pytest-cov

      - name: Build Docker image
        run: |
          cd src
          docker build -t smart_cart:latest .

      - name: Run lint
        run: |
          source venv/bin/activate
          cd src
          make ci-lint

      - name: Run tests
        run: |
          source venv/bin/activate
          cd src
          make ci-test

      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: src
          lcov-file: ./coverage.lcov

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: src/coverage.xml
